tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary-container": "#ffede6",
              "error": "#ba1a1a",
              "on-primary": "#ffffff",
              "on-primary-fixed": "#00174b",
              "tertiary": "#943700",
              "surface-container-low": "#f2f4f6",
              "on-secondary": "#ffffff",
              "surface-container-high": "#e6e8ea",
              "on-surface-variant": "#434655",
              "tertiary-fixed-dim": "#ffb596",
              "on-surface": "#191c1e",
              "on-background": "#191c1e",
              "surface-tint": "#0053db",
              "outline-variant": "#c3c6d7",
              "background": "#f7f9fb",
              "primary-fixed-dim": "#b4c5ff",
              "primary": "#004ac6",
              "on-secondary-container": "#1d3989",
              "tertiary-container": "#bc4800",
              "inverse-surface": "#2d3133",
              "secondary-container": "#8fa7fe",
              "on-tertiary-fixed-variant": "#7d2d00",
              "on-tertiary-fixed": "#360f00",
              "error-container": "#ffdad6",
              "on-error": "#ffffff",
              "secondary-fixed-dim": "#b6c4ff",
              "secondary-fixed": "#dce1ff",
              "surface-container-highest": "#e0e3e5",
              "on-tertiary": "#ffffff",
              "on-secondary-fixed": "#00164e",
              "on-primary-container": "#eeefff",
              "surface-container-lowest": "#ffffff",
              "outline": "#737686",
              "surface-bright": "#f7f9fb",
              "on-error-container": "#93000a",
              "surface-dim": "#d8dadc",
              "on-secondary-fixed-variant": "#264191",
              "tertiary-fixed": "#ffdbcd",
              "surface-variant": "#e0e3e5",
              "secondary": "#4059aa",
              "surface": "#f7f9fb",
              "surface-container": "#eceef0",
              "on-primary-fixed-variant": "#003ea8",
              "inverse-primary": "#b4c5ff",
              "primary-fixed": "#dbe1ff",
              "primary-container": "#2563eb",
              "inverse-on-surface": "#eff1f3"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "container-max-width": "1280px",
              "unit": "8px",
              "section-padding": "80px",
              "margin-mobile": "20px",
              "margin-desktop": "64px",
              "gutter": "24px"
      },
      "fontFamily": {
              "body-lg": ["Inter"],
              "headline-sm": ["Manrope"],
              "label-md": ["Inter"],
              "headline-lg": ["Manrope"],
              "label-sm": ["Inter"],
              "display-lg-mobile": ["Manrope"],
              "body-md": ["Inter"],
              "display-lg": ["Manrope"],
              "body-sm": ["Inter"],
              "headline-md": ["Manrope"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "14px", "fontWeight": "600"}],
              "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}]
      }
    },
  },
}
